apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-deployment.yaml
  - auth-service-deployment.yaml
  - user-service-deployment.yaml
  - analytics-service-deployment.yaml
  - api-gateway-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml 